### ISSUE TITLE
Errors in config.example.json

### ISSUE THREAD

**Issue by notpace** [smart-on-fhir/sample-apps-stu3#8]
* The `config.example.json` file contains an extraneous comma (at the end of line 33)
* As of https://github.com/smart-on-fhir/sample-apps-stu3/pull/7 the `jwks_url` parameter is required. Per the [auth documentation](https://github.com/smart-on-fhir/fhir-bulk-data-docs/blob/master/authorization.md#registering-a-smart-backend-service-communicating-public-keys), direct jwks are allowed, but not preferred

**Comment by vlad-ignatov** [comment]
Either `jwks_url` or `jwks` is required. In other words, `jwks_url` is preferred but not required. The UI will generate a config file that has one of these, depending on your "Authorization" value.

One limitation is that if you want to use the sample client with local `jwks_url` you will have to manually add that to the config file (and keep the `jwks`). Then the client will start a small server to host the public key(s) from the provided `jwks`. This is not very useful, because the key(s) will be hosted on localhost and will only be accessible from local bulk-data servers. It only exist as a proof of concept and for testing purposes. In other words, the remote JWKS concept does not really fit the CLI client use case.

Since yesterday, if your `jwks_url` is not local (not localhost, 0.0.0.0 or 127.0.0.1), then the client will not try to host anything but simply pass it to the backend. This way you can use externally hosted JWKS file like the example one: https://cdn.rawgit.com/smart-on-fhir/fhir-bulk-data-docs/master/sample-jwks/RS384.public.json

**Comment by notpace** [comment]
Thanks for the fixes in 7f15c62c5f05f0d6a48c0fdd450d69c21f00de2c and d545c0e77b578a5918679925a5800542fdbad38d !
